version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AD_Tools
      MYSQL_USER: AtlanteanDragon
      MYSQL_PASSWORD: NotAHardPassword
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - './app:/var/www/'
    depends_on:
      - 'database'
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database
    ports:
      - "8081:80"
    volumes: 
      - "/sessions"
    links:
      - database:database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - './app:/var/www/ad_tools'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - 'php'
      - 'database'    